spring:
  # rabbitmq
  rabbitmq:
    host: 120.79.27.209
    username:
    password:
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
  # qq mail
  mail:
    host: smtp.qq.com
    username: 691409320@qq.com
    password:
#    host: smtp.sendgrid.net
#    username: apikey
#    password: 密钥内容
    default-encoding: utf-8
    port: 587
    properties:
      mail.smtp.auth: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000
      mail.smtp.starttls.enabl: true
  # thymeleaf
  thymeleaf:
    cache: false
  redis:
    #redis数据库，默认是0
    database: 0
    #redis服务器地址
    host: 120.79.27.209
    #redis服务端口，默认6379
    port: 6379
    #redis密码，默认为空
    password:
# +++++++++++++++++++++++ 配置send grid +++++++++++++++++++++++
sendgrid:
  from:
    name: chet
    email:
  api-key:
