server:
  port: 9810

spring:
  application:
    name: service-oss

  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 2MB

#阿里云OSS
#不同的服务器，地址不同
ali-yun:
  oss:
    file:
      endpoint: 
      key-id: 
      key-secret: 
      #bucket可以在控制台创建，也可以使用java代码创建
      bucket-name: 
