server:
  port: 9120
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
#开启SpringBoot Admin的监控
management:
  endpoints:
    web:
      exposure:
        include: '*'